import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function FrontLayout({ children }) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      {children}
    </ThemeProvider>
  );
}
